{% set name = "pyCHX" %}
{% set version = "4.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6a015e9c984189f7bdaba6243e3af4e27f87ee35bece215f3ac4bdb71db1b9fa

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - databroker
    - dill
    - eiger-io
    - h5py
    - historydict
    - ipython
    - lmfit
    - matplotlib-base
    - modestimage
    - numpy
    - pandas
    - pillow
    - pims
    - pytz
    - reportlab
    - scikit-beam
    - scikit-image
    - scipy
    - six
    - tqdm
    - xray-vision

test:
  imports:
    - pyCHX
    - pyCHX.v2
    - pyCHX.v2._commonspeckle
    - pyCHX.v2._futurepyCHX

about:
  home: https://github.com/NSLS-II/pyCHX
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: pyCHX - NSLS-II CHX XPCS Data Analysis Package

extra:
  recipe-maintainers:
    - mrakitin
    - kbeeperez
    - conda-forge/event-model
